import Head from 'next/head';
import FridgeFreezerSection from 'src/components/template/FridgeFreezerSection';
import AddFoodSection from 'src/components/template/AddFoodSection';

const MyFridge = () => {
  return (
    <>
      <Head>
        <title>In my fridge</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <FridgeFreezerSection />
      <AddFoodSection />
    </>
  );
};

export default MyFridge;
