import { faChevronRight, faUser } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Head from 'next/head';
import tw from 'tailwind-styled-components';

const Setting = () => {
  return (
    <>
      <Head>
        <title>Setting</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Section>
        <Title>나의 정보</Title>
        <MyInfo>
          <ProfileImg>
            <ArrowIcon role='button' icon={faUser} size='lg' />
          </ProfileImg>
          <Info>
            <Id>집밥좀잘해먹고싶은1인</Id>
          </Info>
        </MyInfo>

        <Title>설정</Title>
        <List>
          <Item>
            <ItemTitle>식재료 아이콘 크기 설정</ItemTitle>
            <ItemInfo>예정</ItemInfo>
            <ArrowIcon role='button' icon={faChevronRight} />
          </Item>
          <Item>
            <ItemTitle>냉장고 보기 설정</ItemTitle>
            <ItemInfo>예정</ItemInfo>
            <ArrowIcon role='button' icon={faChevronRight} />
          </Item>
          <Item>
            <ItemTitle>냉장칸 커스텀 설정</ItemTitle>
            <ItemInfo>예정</ItemInfo>
            <ArrowIcon role='button' icon={faChevronRight} />
          </Item>
          <Item>
            <ItemTitle>냉동칸 커스텀 설정</ItemTitle>
            <ItemInfo>예정</ItemInfo>
            <ArrowIcon role='button' icon={faChevronRight} />
          </Item>
          <Item>
            <ItemTitle>즐겨찾기 식재료 설정</ItemTitle>
            <ItemInfo>예정</ItemInfo>
            <ArrowIcon role='button' icon={faChevronRight} />
          </Item>
          <Item>
            <ItemTitle>유통기한 임박 알림 설정</ItemTitle>
            <ItemInfo>예정</ItemInfo>
            <ArrowIcon role='button' icon={faChevronRight} />
          </Item>
        </List>
      </Section>
    </>
  );
};

const Section = tw.section`
  desktop:w-2/6
  tablet:w-3/6
  mobile:p-3
  m-auto
`;

const Title = tw.h1`
  flex
  items-center
  gap-1
  text-[14px]
  text-orange
  mobile:py-2
  pl-1
`;
const MyInfo = tw.div` 
bg-white-dark
  shadow-lg
  flex
  gap-3
  p-3
  mobile:mb-5
  rounded-2xl
`;
const ProfileImg = tw.div`
  flex
  justify-center
  items-center
  w-12
  h-12
  rounded-lg
  bg-green
  shadow-lg
`;
const Info = tw.div`
  flex 
  flex-col
  justify-center
  w-4/5
`;
const Id = tw.span`
  text-base
`;
const List = tw.ul`
  flex
  flex-col
  gap-2
  
`;
const Item = tw.li`
  hover:bg-yellow-light
  cursor-pointer
  rounded-xl
  bg-white-dark
  py-3
  px-4
  border
  border-b-gray-light
  flex
  items-center
  justify-between
  text-[14px]
`;
const ItemTitle = tw.span`
  w-10/12
`;
const ItemInfo = tw.span`
  text-gray
`;
const ArrowIcon = tw(FontAwesomeIcon)`
  pb-0.5
`;

export default Setting;
