import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import tw from 'tailwind-styled-components';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>What is in the fridge?</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>Hi</div>
    </div>
  );
}
