import Head from 'next/head';
import tw from 'tailwind-styled-components';
import styled from 'styled-components';

const Container = styled.div`
  background-color: #f6ffed;
  min-height: 100vh;
`;

const Title = styled.div`
  color: orange;
`;

const TwTitle = tw.h1`
  text-red-600
  m-20
`;

const myFridge = () => {
  return (
    <Container>
      <Head>
        <title>In my fridge</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Title>In my fridge</Title>
    </Container>
  );
};

export default myFridge;
