import Head from 'next/head';
import tw from 'tailwind-styled-components';
import AddFoodSection from '../components/template/AddFoodSection';

const MyFridge = () => {
  return (
    <>
      <Head>
        <title>In my fridge</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <FridgeSection>냉장고 박스입니다.</FridgeSection>
      <AddFoodSection />
    </>
  );
};

const FridgeSection = tw.section``;

export default MyFridge;
