import Head from 'next/head';
import tw from 'tailwind-styled-components';

const Title = tw.h1`
  text-2xl 
  font-bold 
`;

const myFridge = () => {
  return (
    <div>
      <Head>
        <title>In my fridge</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Title>In my fridge</Title>
    </div>
  );
};

export default myFridge;
